### ISSUE TITLE
Если сериализую таблицу значений, в строке которой содержится картинка или двоичные данные, то вылетает ошибка

### ISSUE THREAD

**Issue by LevkinSergey** [arkuznetsov/SerLib1C#1]

**Comment by LevkinSergey** [comment]
{УниверсальныеИнструменты Обработка.УИ_ПреобразованиеДанныхJSON.МодульОбъекта(48)}: Значение не является значением объектного типа (ПолноеИмя)

**Comment by LevkinSergey** [comment]
Происходит при попытке сериализовать таблицу истории в консоли HTTP

**Comment by arkuznetsov** [comment]
> Происходит при попытке сериализовать таблицу истории в консоли HTTP

А можешь поподробнее описать контекст и порядок воспроизведения проблемы?

**Comment by LevkinSergey** [comment]
сериализатор использую в подсистеме https://github.com/cpr1c/tools_ui_1c. версия 0.6.1. 
Сериализую таблицу вида 
![image](https://user-images.githubusercontent.com/36307272/74656926-3a1fc800-51a0-11ea-9871-238ccd7e5c57.png)
Но в которую добавлены колонки
ТелоЗапросаДвоичныеДанные вместо ТелоЗапросаАдресДвоичныхДанных
ТелоОтветаДвоичныеДанные вместо ТелоОтветаАдресДвоичныхДанных
ТелоОтвета вместо АдресТелаОтветаСтрокой


Для сериализации выполняю код 


```
СериализаторJSON=Обработки.УИ_ПреобразованиеДанныхJSON.Создать();
	СтруктураИстории=СериализаторJSON.ЗначениеВСтруктуру(ТаблицаЗначенийИстории);
	JSONСтрокаИстории=СериализаторJSON.ЗаписатьОписаниеОбъектаВJSON(СтруктураИстории);

```
При выполнение сериализации в структуру выдает ошибку на проверке ссылочный это тип или нет.

Если еще чего нужно, готов предоставить

**Comment by arkuznetsov** [comment]
@LevkinSergey 
залил в Develop, если ручками, [то нужно поправить так](https://github.com/arkuznetsov/SerLib1C/commit/66abfe8896aad964582c49b0e8fd418d083f38a0#diff-d3ec98f8b373c82e2f3f343580311fb0L42-L48)

**Comment by arkuznetsov** [comment]
@LevkinSergey Удалось проверить?

**Comment by LevkinSergey** [comment]
пока нет. Сегодня проверю

**Comment by LevkinSergey** [comment]
Проблема ушла. Спасибо
