### ISSUE TITLE
Вопрос: исключение стандартных реквизитов объектов

### ISSUE THREAD

**Issue by d-hurricane** [arkuznetsov/SerLib1C#13]
Почему при преобразовании справочника-объекта в структуру часть его стандартных реквизитов можно отфильтровать (пометка удаления, это группа), а часть - обязательно выгрузится, не взирая на указанные исключения свойств (родитель, владелец и т.п.)?

**Comment by arkuznetsov** [comment]
Нет ответа, видимо так получилось. :-)
